version: '3.8'
services:
    db-ms-usuario:
        container_name: postgres
        image: postgres
        restart: always
        volumes:
        -   ./resources/build-database.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: database_user
            POSTGRES_PASSWORD: TWSsy9Le647u9wnU
            POSTGRES_DATABSAE: postgres
        ports:
            - '5432:5432'

    rabbit-mq:
        container_name: rabbit-mq
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"