version: '3.8'
services:
    db-ms-usuario:
        container_name: postgres
        image: postgres
        restart: always
        volumes:
        -   ./resources/build-database.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: database_user
            POSTGRES_PASSWORD: TWSsy9Le647u9wnU
            POSTGRES_DATABSAE: postgres
        ports:
            - '5432:5432'

    rabbit-mq:
        container_name: rabbit-mq
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"

    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:latest
        volumes:
            - ./resources/keycloak:/opt/jboss/keycloak/imports
        command:
            - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: db-ms-usuario
            DB_DATABASE: keycloak-db
            DB_USER: keycloak_application
            DB_SCHEMA: public
            DB_PASSWORD: FNvJ1ThgdcvU390G
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: keycloakpass
            # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
            #JDBC_PARAMS: "ssl=true"
        ports:
            - 8080:8080
        depends_on:
            - db-ms-usuario
