server:
  port: 8081

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowCredentials: true
            allowedOrigins: "http://localhost:3001"
            allowedMethods:
              - POST
              - GET
              - OPTIONS
      routes:
        - id: bcra
          uri: http://localhost:9010/
          predicates:
            - Path=/bcra/**
          allowed-origins:
          filters:
            - RewritePath=/bcra, /api
        - id: pedido
          uri: http://localhost:9002/
          predicates:
            - Path=/pedido/**
          filters:
            - RewritePath=/pedido, /api
        - id: producto
          uri: http://localhost:9001/
          predicates:
            - Path=/producto/**
          filters:
            - RewritePath=/producto, /api
        - id: cuenta
          uri: http://localhost:9003/
          predicates:
            - Path=/cuenta/**
          filters:
            - RewritePath=/cuenta, /api
        - id: usuario
          uri: http://localhost:9000/
          predicates:
            - Path=/usuario/**
          filters:
            - RewritePath=/usuario, /api
