server:
  port: ${PROXY_PORT:8081}

spring:
  application:
    name: PROXY
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowCredentials: true
            allowedOrigins: "http://${FRONTEND_HOST:localhost}:${FRONTEND_PORT:4200}"
            allowedMethods:
              - POST
              - GET
              - OPTIONS
      routes:
        - id: BCRA
          uri: http://${BCRA_HOST:localhost}:${BCRA_PORT:localhost}/
          predicates:
            - Path=/api/bcra/**
          allowed-origins:
          filters:
            - RewritePath=/api/bcra, /api
        - id: PEDIDO
          uri: lb://PEDIDO
          predicates:
            - Path=/api/pedido/**
          filters:
            - RewritePath=/api/pedido, /api
        - id: PRODUCTO
          uri: lb://PRODUCTO
          predicates:
            - Path=/api/producto/**
          filters:
            - RewritePath=/api/producto, /api
        - id: CUENTA
          uri: lb://CUENTA
          predicates:
            - Path=/api/cuenta/**
          filters:
            - RewritePath=/api/cuenta, /api
        - id: USUARIO
          uri: lb://USUARIO
          predicates:
            - Path=/api/usuario/**
          filters:
            - RewritePath=/api/usuario, /api

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8082}/eureka